### ISSUE TITLE
This project looks interesting, what does it do?

### ISSUE THREAD

**Issue by jpwhitney** [gitlight/gitlight#9]
I was looking around for ways to better utilize Gitolite3 and came across this repo which has a lot of new activity and seems like it's just getting started. I realize the docs are not available yet, however I am interested to see if this would be a more elegant way of using gitolite than the current methods I've discovered.

What does this project intend to do/be? I'm curious to see if I can use it for my purposes.

all the best!

**Comment by MTecknology** [comment]
Howdy!

At this point, gitlight is mostly an exercise in spending as much time as possible in the planning phase of a project. The goal is a read-only web front-end to gitolite3. The idea being, gitolite does a really excellent job and port 22, and staying read-only eliminates security concerns. Instead, the app just facilitates collaboration.

There's #gitlight on freenode if you're interested. At the moment, this is just an idea I'm working toward in my spare time.

**Comment by MTecknology** [comment]
I've provided a more clear vision of this project's goal. It'll show up in the documentation whenever I figure out how to handle pygit2 issues on readthedocs.org.

For now: https://github.com/gitlight/gitlight/blob/develop/docs/index.rst
